AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
Resources:
  GetExampleDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://capstone-mndt-artifacts/8d6619962b6351ce51a52e8ceb6fbb54
      Handler: com.kenzie.capstone.service.lambda.GetExampleData
      Runtime: java11
      Description: Get Example Data for given id
      MemorySize: 512
      Timeout: 240
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /example/{id}
            Method: get
  SetExampleDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://capstone-mndt-artifacts/8d6619962b6351ce51a52e8ceb6fbb54
      Handler: com.kenzie.capstone.service.lambda.SetExampleData
      Runtime: java11
      Description: Set Example Data
      MemorySize: 512
      Timeout: 240
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /example/
            Method: post
  SendEmailRemindersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://capstone-mndt-artifacts/8d6619962b6351ce51a52e8ceb6fbb54
      Handler: com.kenzie.capstone.service.lambda.SendEmailReminder
      Runtime: java11
      Description: Send daily journal reminders
      MemorySize: 512
      Timeout: 240
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /user/email/reminder/
            Method: post
